"""fix processing enum value

Revision ID: c9d77fe9ccc9
Revises: 502ced50318c
Create Date: 2026-03-06 21:51:35.978471

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'c9d77fe9ccc9'
down_revision: str | Sequence[str] | None = '502ced50318c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
